
trigger:
- main

variables:
#  DebugArguments: ' --filter "TestCategory!=ABC" --verbosity normal '
#  ReleaseArguments: ' --filter "TestCategory!=ABC" --verbosity normal '
  VmImage: vs2017-win2016 # https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops

jobs:
- template:  templates/static-tools.yml
  parameters:
    BuildConfiguration: Release
    VmImage: $(VmImage)