version: "3.9"
services:
  hawaii:
    image: "hawaiiacr.azurecr.io/hawaii:latest"
    ports:
      - "5000:5000"
    volumes:
      - "./DataGateway.Service/cosmos-config.json:/App/cosmos-config.json"
      - "./DataGateway.Service/hawaii-config.cosmos.json:/App/hawaii-config.Cosmos.json"
      - "./DataGateway.Service/schema.gql:/App/schema.gql"
