version: "3.9"
services:
  hawaii:
    image: "hawaiiacr.azurecr.io/hawaii:latest"
    ports:
      - "5000:5000"
    volumes:
      - "./DataGateway.Service/appsettings.cosmos.json:/App/appsettings.json"
      - "./DataGateway.Service/cosmos-config.json:/App/config.json"
