version: "3.9"
services:
  hawaii:
    image: "hawaiiacr.azurecr.io/hawaii/refs/heads/main:latest"
    ports:
      - "5000:5000"
    volumes:
      - "../src/Service/dab-config.MySql.json:/App/dab-config.json"
