# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

trigger:
  batch: true
  branches:
    include:
    - main
    - gh-readonly-queue/main
    - release/*

pr:
  branches:
    include:
    - main
    - release/*
  paths:
    exclude:
    - samples/**
    - docs/**
    - '*.md'
    - templates/**

variables:
#  DebugArguments: ' --filter "TestCategory!=ABC" --verbosity normal '
#  ReleaseArguments: ' --filter "TestCategory!=ABC" --verbosity normal '
  VmImage: windows-2022 # https://learn.microsoft.com/azure/devops/pipelines/agents/hosted?view=azure-devops

jobs:
- template:  templates/static-tools.yml
  parameters:
    BuildConfiguration: Release
    VmImage: $(VmImage)
